version: "3.8"

services:
  shlink:
    image: shlinkio/shlink:4
    environment:
      - TZ=America/Sao_Paulo
      - DEFAULT_DOMAIN=short.i92tecnologia.com.br
      - IS_HTTPS_ENABLED=true
      - TRUSTED_PROXIES=*
      - DB_DRIVER=postgres
      - DB_HOST=postgres_postgres
      - DB_PORT=5432
      - DB_NAME=shlink
      - DB_USER=shlink_user
      - DB_PASSWORD=Shl1nk_i92T3ch_2026!
      - INITIAL_API_KEY=e3fc0910a3cb9bb0a5bba26bae1a45fc0d6d5f9a7dec21adc31fcfad21210e73
      - GEOLITE_LICENSE_KEY=
    networks:
      - network_swarm_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.manager == true
      labels:
        - traefik.enable=true
        - traefik.http.routers.shlink.rule=Host(`short.i92tecnologia.com.br`)
        - traefik.http.routers.shlink.entrypoints=websecure
        - traefik.http.routers.shlink.tls=true
        - traefik.http.routers.shlink.tls.certresolver=letsencryptresolver
        - traefik.http.routers.shlink.service=shlink
        - traefik.http.services.shlink.loadbalancer.server.port=8080
        - traefik.docker.network=network_swarm_public
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
